#!/usr/bin/env bash
echo "This is the git add command."

# The command's name
echo -e 'git add'

# the command's description
echo "The Git add command takes all of the content changes in the working tree and adds them to the index for committing. Git add is used to add new untracked files and modified files to index."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "ALL OPTIONS: git add [--verbose | -v] [--dry-run | -n] [--force | -f] [--interactive | -i] [--patch | -p]
    [--edit | -e] [--[no-]all | --[no-]ignore-removal | [--update | -u]]
    [--intent-to-add | -N] [--refresh] [--ignore-errors] [--ignore-missing]
    [--] [<pathspec>…​]"
echo "EXAMPLE OPTIONS: git add --all -v"
echo -e "\t--all: this tell git to add all changes to the staging area."
echo -e "\t-v: This tells git to show informational messages about all the changes being added to the staging area."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
