#!/usr/bin/env bash
echo "This is the git branch command."

# The command's name
echo -e 'git branch'

# the command's description
echo "This command allows you to create, list or delete branches in git. Branching allows the manage many parts of a project in one repository and merge them together. When used correctly branching makes it easy for multiple persons to work on a project in a seamless and un-intrusive way. "

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
