#!/usr/bin/env bash
echo "This is the git checkout command."

# The command's name
echo -e 'git checkout'

# the command's description
echo "description here"

echo "git checkout is a command to update files in the working tree to match the version in the index or the specified tree. "

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git checkout development"
echo "This command will switch the current branch you are working on the a branch named development (if a branch named development exists)."

# example 2
echo "git checkout -b dev"
echo "This command will create a branch called dev and changes the current branch being worked on the the dev branch."


exit 0
