#!/usr/bin/env bash
echo "This is the git commit command."

# The command's name
echo -e 'git commit'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "ALL OPTIONS: git commit [-a | --interactive | --patch] [-s] [-v] [-u<mode>] [--amend]
                  [--dry-run] [(-c | -C | --fixup | --squash) <commit>]
                  [-F <file> | -m <msg>] [--reset-author] [--allow-empty]
                  [--allow-empty-message] [--no-verify] [-e] [--author=<author>]
                  [--date=<date>] [--cleanup=<mode>] [--[no-]status]
                  [-i | -o] [-S[<keyid>]] [--] [<file>...]"
echo "SYNTAX EXAMPLE: git commit --date=<date> -m <Commit Message>"
echo -e "\t--date: this option allows the user to specify a date for the commit."
echo -e "\t-m: this option allows the user to add a message about the commit."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
