#!/usr/bin/env bash
echo "This is the git config command."

# The command's name
echo -e 'git config'

# the command's description
echo "This command allows you to view and set options for a repository or the global git environment. The configuration options recognized by Git fall into two categories: client-side and server-side. The majority of the options are client-side – configuring a user's personal working preferences."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
