#!/usr/bin/env bash
echo "This is the git fetch command."

# The command's name
echo -e 'git fetch'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git fetch origin"
echo "This command will copy all new branches and tags from the remote server (origin) and store them in your local repository."

# example 2
echo "git fetch origin +lists:references maint:compatiblity"
echo "This command updates or creates the branches references and compatibility in the local repository by fetching from the branches lists and maint respectively."


exit 0
