#!/usr/bin/env bash
echo "This is the git init command."

# The command's name
echo -e 'git init'

# the command's description
echo "This command creates an empty Git repository. This means that it creates a new folder in your directory name '.git' and addes all the files and subfolders needed to begin tracking any changes that were made. 
This command can also be used to to move an existing repository to another location."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
