#!/usr/bin/env bash
echo "This is the git log command."

# The command's name
echo -e 'git log'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git log --no-merges -n <NUMBER>"
echo -e "\t--no-merges: shows the history of changes excluding any merges that occured."
echo -e "\t-n <NUMBER>: only shows the most recent number of changes specified by <NUMBER>."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
