#!/usr/bin/env bash
echo "This is the git reset command."

# The command's name
echo -e 'git reset'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git reset --soft HEAD^"
echo "This example will undo the last commit made by a user. The --soft option here ensures that the files remain untouched, only the commit is undone. A good time to use this command would be when there is a spelling error in the commit message."

# example 2
echo "git reset HEAD test.md"
echo "This example removes test.md from the staging area."


exit 0
