#!/usr/bin/env bash
echo "This is the git rm command."

# The command's name
echo -e 'git rm'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git rm [options] <file>"
echo -e "\t-n: Performs a dry-run; does not actually the delete the file."
echo -e "\t-r: Recursively remove contents if a directory is specified."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git rm file.txt"
echo "This command removes the file named file.txt from the index.

# example 2
echo "git rm Documentation/\*.txt"
echo "This command removes all *.txt files from the index that are under the Documentation directory and any of its subdirectories."


exit 0
