#!/usr/bin/env bash
echo "This is the git status command."

# The command's name
echo -e 'git status'

# the command's description
echo "The git status command displays the state of the working directory and the staging area. It displays changes which have been staged, which haven’t, and which files aren’t being tracked by Git. "

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git status -s"
echo "This example shows the results of the git status command in short format. Normally when we view changes we see a message saying

	modified: .....

The -s flag shortens the messaged to say

	M: ......"

# example 2
echo "git status -b"
echo "This example shows the results of the git status command however it also shows the branch on which changes were made."


exit 0
