#!/usr/bin/env bash
echo "This is the alias command."

# The command's name
echo -e 'alias'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "alias ll='ls -l'"
echo "This command will allow a user to type the characters ll and this would list all files in the directory in long format."

# example 2
echo "alias ..='cd ..'"
echo "This alias will allow a user to type the character .. and this would change to one directory above the current one."


exit 0
