#!/usr/bin/env bash
echo "This is the cd command."

# The command's name
echo -e 'cd'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "cd home"
echo "Assume that the current direcotry is the root directory of the filesystem denoted by `/`. To navigate to the home directory which is one level down from the root directory the above command can be used."

# example 2
echo "cd home/Pictures"
echo "It is possible to access any directory on the filesystem by typing the `cd` command, followed by the full path to the desired folder. To go straight to the `Pictures` directory from the root directory (`/`) the above command can be used."


exit 0
