#!/usr/bin/env bash
echo "This is the chmod command."

# The command's name
echo -e 'chmod'

# the command's description
echo "This command stands for [change mode] and changes the permissions on files and folder for various users of the system. This means that it allows you to set the rules for each file/folder and this determines who can access it and how it can be accessed."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
