#!/usr/bin/env bash
echo "This is the chmod command."

# The command's name
echo -e 'chmod'

# the command's description
echo "This command stands for [change mode] and changes the permissions on files and folder for various users of the system. This means that it allows you to set the rules for each file/folder and this determines who can access it and how it can be accessed."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "chmod [OPTION]... MODE[,MODE]... FILE...
       chmod [OPTION]... OCTAL-MODE FILE...
       chmod [OPTION]... --reference=RFILE FILE..."
echo "chmod <user/group>+<permission> <file>"
echo -e "\t<user/group> : this option states which users or groups are receiving the permissions"
echo -e "\t<permission>: these are the permissions themselves and they are represented by letters r,w,x (read, write, execute)"
echo -e "\t<file>: this is the file that we are defining permissions on."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
