#!/usr/bin/env bash
echo "This is the clear command."

# The command's name
echo -e 'clear'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "clear"
echo -e "\tThis command has no additional options."

#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
