#!/usr/bin/env bash
echo "This is the cp command."

# The command's name
echo -e 'cp'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "cp main.js main1.js"
echo "In this example, the cp command is used to make a copy of the main.js file and store it as main1.js "

# example 2
echo "cp ~/pictures/picture-*.jpg ~/picture-backup"
echo "Here the cp command is used to copy multiple files and folders at once based on a pattern. The command is used to copy all the .jpg files that start with the word 'picture' from the pictures directory into the picture-backup directory."


exit 0
