#!/usr/bin/env bash
echo "This is the curl command."

# The command's name
echo -e 'curl'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "curl -o index.html study.moderndeveloper.com"
echo "Using curl with the -o flag allows the user to save the contents of the web page at study.moderndeveloper.com to the file named index.html."

# example 2
echo "curl -L study.moderndeveloper.com"
echo "By default, curl doesn't process redirects. This means that if a page is moved, the curl command will not be able to access its new location. Using the -L flag, the curl command can follow the HTTP Location headers and redirects to the new location where the web page is stored. "


exit 0
