#!/usr/bin/env bash
echo "This is the exit command."

# The command's name
echo -e 'exit'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "$ exit"
echo -e "\$ exit: exit the shell"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
