#!/usr/bin/env bash
echo "This is the find command."

# The command's name
echo -e 'find'

# the command's description
echo "The find command is used to search for files and directories via the command line. It can be used to find files based on search criteria like name, ownership, date/time, size and much more. This command can also be used in conjunction with other commands to perform operations on the files that match the search results."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
