#!/usr/bin/env bash
echo "This is the find command."

# The command's name
echo -e 'find'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "$ find [pathnames] [conditions]"
echo -e "\$ find -name "text1.txt": Find text1.txt file"
echo -e "\$find -maxdepth 2 -name "text1.txt": Find text1.txt file in the current directory and one level down to the current directory."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
