#!/usr/bin/env bash
echo "This is the for command."

# The command's name
echo -e 'for'

# the command's description
echo "A ‘for loop’ is a bash programming language statement which allows code to be repeatedly executed. A for loop is classified as an iteration statement which means it is the repetition of a process within a bash script."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "for [condition] do ... done"
echo -e "\t[condition] - this is the condition that must be met for the loop to continue. An example of a condition will be to perform the loop until a varible equals 5 with the variable starting at 1 and being incremented by 1 with every loop."
echo -e "\t[...] - this is the action the user would like to perform with each loop."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
