#!/usr/bin/env bash
echo "This is the grep command."

# The command's name
echo -e 'grep'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "grep [OPTIONS] PATTERN [FILE...]"
echo "grep [-m NUM] ['word'] file.txt"
echo -e "\t-m NUM: This option tells the grep command to stop reading the file (file.txt) after NUM lines containing the pattern being searched for are found."
echo -e "\t'word': This is the pattern that the grep command is searching for within file.txt."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
