#!/usr/bin/env bash
echo "This is the grep command."

# The command's name
echo -e 'grep'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "$ grep -w "test" test1.txt"
echo "Search the file test1.txt for lines containing the word "test"."

# example 2
echo "$ grep -cw "test" test1.txt"
echo "Displays a count of how many lines in test1.txt contains "test"."


exit 0
