#!/usr/bin/env bash
echo "This is the ls command."

# The command's name
echo -e 'ls'

# the command's description
echo "The `ls` command displays an alphabetically ordered list of the files and folders in the current directory and information about those files and folders. 
When used with any of its many options, the `ls` command can be made to filter and sort the results it displays based on a variety of criteria. "

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
