#!/usr/bin/env bash
echo "This is the ls command."

# The command's name
echo -e 'ls'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "$ ls [options] [file|dir]"
echo -e "\$ ls -a: list all files including hidden file starting with '.'"
echo -e "\$ ls -d */: List directories only"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
