#!/usr/bin/env bash
echo "This is the man command."

# The command's name
echo -e 'man'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "man ls"
echo "This command will show the manual page for the ls program, allowing the user to see how the ls program works and how to use it."

# example 2
echo "man 5 passwd"
echo "The manual page for the passwd command has many sections. This example will begin the man page at section 5. This is useful if the user knows which section of the manual page contains the information they seek. "


exit 0
