#!/usr/bin/env bash
echo "This is the mkdir command."

# The command's name
echo -e 'mkdir'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "$ mkdir [option] directory_name(s)"
echo -e "\$ mkdir -p food/fruit/citrus/oranges: Creates the intermediate directories for a new directory if parent directories are not exist."
echo -e "\$ mkdir dir_1 dir_2 dir_3: Creates three directories under current directory."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
