#!/usr/bin/env bash
echo "This is the mkdir command."

# The command's name
echo -e 'mkdir'

# the command's description
echo "This command is short for [make directory] and is used to create new folders or directories via the command line, if they do not already exist. If the directory already exists, an error message is shown. The mkdir command can also be used to create multiple directories at once."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
