#!/usr/bin/env bash
echo "This is the mv command."

# The command's name
echo -e 'mv'

# the command's description
echo "mv (Move) is a command to move one or more files or directories from one directory to another directory. It can also rename files or directories."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
