#!/usr/bin/env bash
echo "This is the ping command."

# The command's name
echo -e 'ping'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "ping [ -LRUbdfnqrvVaAB] [ -c count] [ -i interval] [ -l preload] [ -p pattern] [ -s packetsize] [ -t ttl] [ -w deadline] [ -F flowlabel] [ -I interface] [ -M hint] [ -Q tos] [ -S sndbuf] [ -T timestamp option] [ -W timeout] [ hop ...] destination
"
echo "ping i <NUM> <address>"
echo -e "\ti: this option determines the interval between pings set by <NUM>. If NUM was 5 then the ping would be executed once every 5 seconds."
echo -e "\t<address>: This is the network location that we would like to ping. eg. http://google.com"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
