#!/usr/bin/env bash
echo "This is the pipe command."

# The command's name
echo -e 'pipe'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "$ command 1 | command 2"
echo -e "\$ ls -al | more :Create a long list of files and piping the output into the Linux more command."
echo -e "\$ lps aux | wc -l :Display how many processes are currently running on your system."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
