#!/usr/bin/env bash
echo "This is the rm command."

# The command's name
echo -e 'rm'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "$ rm [OPTION]... FILE..."
echo -e "\$ rm -i: Prompt before every removal."
echo -e "\$ rm -r: Remove directories and their contents recursively."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
