#!/usr/bin/env bash
echo "This is the rmdir command."

# The command's name
echo -e 'rmdir'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "rmdir [-p] [-v] path/to/directory"
echo -e "\t-p: This option removes the 'directory' folder as well as its parent folders ('path' and 'to') once the 'directory' folder is empty."
echo -e "\t-v: This option removes the 'directory' folder once it is empty and also shows a message while executing the command. The message looks something like this: removing directory, ‘/path/to/directory’ "
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
