#!/usr/bin/env bash
echo "This is the rmdir command."

# The command's name
echo -e 'rmdir'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "$ rmdir test1"
echo "Directory test1 is removed from current path."

# example 2
echo "$ rmdir -p dir1/dir2/dir3"
echo "Delete nested directories dir1/dir2/dir3"


exit 0
