#!/usr/bin/env bash
echo "This is the ssh command."

# The command's name
echo -e 'ssh'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "ssh -v"
echo "This command displays the SSH client currently running and it’s corresponding version number"

# example 2
echo "ssh imanuel@remotehost.com"
echo "This command connects to the server at remotehost.com with the username imanuel."


exit 0
