#!/usr/bin/env bash
echo "This is the tar command."

# The command's name
echo -e 'tar'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "tar [-] A --catenate --concatenate | c --create | d --diff --compare | 
    --delete | r --append | t --list | --test-label | u --update | 
    x --extract --get [options] [pathname ...]"
echo "tar -xf <file> -C <directory>"
echo -e "\t-x: x is one of the function letter that tells the tar command how to behave. x makes the command do an extract."
echo -e "\tf: f is one of the options of the tar command. It tells tar to perform the function specified by the preceding letter a named file."
echo -e "\t-C: this is another option that tell the tar command to change to the specified directory before executing the preceding commands."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
