#!/usr/bin/env bash
echo "This is the tar command."

# The command's name
echo -e 'tar'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "$ tar cf archive.tar text1.txt text2.txt"
echo "create an archive.tar file for text1.txt and text2.txt file"

#example 2
echo "$ tar -xvzf archive.tar"
echo "Extract archive.tar file"


exit 0
