#!/usr/bin/env bash
echo "This is the touch command."

# The command's name
echo -e 'touch'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "$ touch test1.txt"
echo "If test1.txt exists, updates file's access and modification times to the current time."
echo "If file.txt doesn't exist, create a new, empty txt file."

# example 2
echo "$ touch -a test1.txt"
echo "Only change the access time for the test1.txt file."


exit 0
