#!/usr/bin/env bash
echo "This is the variables command."

# The command's name
echo -e 'variables'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "VARNAME=VALUE"
echo -e "\tVARNAME: the name of the variable being defined for eay reference."
echo -e "\tVALUE: the value of the variable being defined. This value can be of different types - string, integer, boolean, array."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
