#!/usr/bin/env bash
echo "This is the wc command."

# The command's name
echo -e 'wc'

# the command's description
echo "This command prints the amount of new lines, words and bytes contained within a file. If more than one file is specified, it gives a total count for all the files. The output is similar to a table and counts are always in the following order: newline, word, character, byte, maximum line length. "

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
