#!/usr/bin/env bash
echo "This is the wc command."

# The command's name
echo -e 'wc'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "$ wc [OPTION]... [FILE]..."
echo -e "\$ wc -c: print the byte counts."
echo -e "\$ wc -m: print the character counts."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
