#!/usr/bin/env bash
echo "This is the while command."

# The command's name
echo -e 'while'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "while [ condition ]
do
   command1
   command2
   command3
done"

echo -e "make sure it condition will always be met to help prevent an endless loop."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "
i="0"
while [ $i -lt 4 ]
do
echo $i
i=$[$i+1]
done"

echo "This example will print the numbers 0,1,2,3,4 to the screen."

# example 2
echo "
i="10"
while [ $i -gt 3 ]
do
echo $i
i=$[$i-1]
done"

echo "This example will print the numbers 10,9,8,7,6,5,4 to the screen."


exit 0
