#!/usr/bin/env bash
echo "This is the while command."

# The command's name
echo -e 'while'

# the command's description
echo "The while loop is a construct that allows for repetitive execution of commands as long as the condition controlling the while loop is not met. An example of a condition may be to continue executing the instructions while a variable is less than 10. It is important that the condition controlling the while loop be met eventually, to avoid the situation where the while loop never stops until the machine runs out of memory."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "
i="0"
while [ $i -lt 4 ]
do
echo $i
i=$[$i+1]
done"

echo "This example will print the numbers 0,1,2,3,4 to the screen."

# example 2
echo "
i="10"
while [ $i -gt 3 ]
do
echo $i
i=$[$i-1]
done"

echo "This example will print the numbers 10,9,8,7,6,5,4 to the screen."


exit 0
