#!/usr/bin/env bash
echo "This is the whoami command."

# The command's name
echo -e 'whoami'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "whoami Examples"
echo "$ whoami"
echo "Neverland"
echo "Display current User name"



exit 0
