#!/usr/bin/env bash
echo "This is the whoami command."

# The command's name
echo -e 'whoami'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "whoami [--help] [--version]"
echo -e "\t--help: displays the man page for the whoami command."
echo -e "\t--version: displays the version number of the whoami command."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
